In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Step 1: Original dataset load

In [2]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM-AI/data/raw/customer .csv")

In [3]:
df.shape

(50000, 28)

In [4]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Location', 'Membership',
       'RegistrationDate', 'Tenure', 'TotalSpend', 'TotalTransactions',
       'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
       'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
       'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
       'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating',
       'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore',
       'ChurnRisk'],
      dtype='str')

In [5]:
remove_cols =[ 
            "CustomerID",
            "RegistrationDate",
            "ChurnRisk"
             ]

In [6]:
df_model = df.drop(
    columns=remove_cols,
    errors='ignore'
)

In [7]:
df_model.head()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
0,54,Female,72543.43,NJ,Gold,6.81,4389.80,30,146.33,3,...,14.0,48.5,65.6,79,65,3.2,0,2,8.0,31.8
1,42,Male,78149.18,AZ,Silver,5.14,706.89,2,353.45,2,...,7.0,87.9,23.4,0,1,0.0,5,18,0.0,11.6
2,24,Female,48635.85,MD,Free,0.37,2935.65,20,146.78,3,...,50.0,87.8,62.3,24,55,2.8,7,1,23.0,18.2
3,31,Male,19935.67,GA,Free,1.11,1410.68,32,44.08,2,...,30.0,73.0,32.0,23,74,3.7,5,3,3.0,21.0
4,45,Female,83500.57,AZ,Silver,6.80,4352.92,69,63.09,5,...,19.0,25.5,59.0,38,77,3.8,4,2,17.0,36.4

In [8]:
df_model.isnull().sum()

Age                       0
Gender                    0
Income                 2236
Location                  0
Membership                0
Tenure                    0
TotalSpend                0
TotalTransactions         0
AverageOrderValue         0
PurchaseFrequency         0
LastPurchaseDays          0
PreferredCategory         0
WebsiteVisits             0
AppUsageMinutes           0
LoginFrequency            0
WishlistCount          1110
CartAbandonmentRate    1253
EmailOpenRate          2402
MarketingClicks           0
SatisfactionScore         0
Rating                 1824
SupportCalls              0
Complaints                0
Reviews                2375
CustomerHealthScore       0
dtype: int64

In [9]:
num_cols = df_model.select_dtypes(
    include=np.number
).columns

In [10]:
for col in num_cols:
    df_model[col] = df_model[col].fillna(
        df_model[col].median()
    )

In [11]:
df_model.isnull().sum()

Age                    0
Gender                 0
Income                 0
Location               0
Membership             0
Tenure                 0
TotalSpend             0
TotalTransactions      0
AverageOrderValue      0
PurchaseFrequency      0
LastPurchaseDays       0
PreferredCategory      0
WebsiteVisits          0
AppUsageMinutes        0
LoginFrequency         0
WishlistCount          0
CartAbandonmentRate    0
EmailOpenRate          0
MarketingClicks        0
SatisfactionScore      0
Rating                 0
SupportCalls           0
Complaints             0
Reviews                0
CustomerHealthScore    0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
cat_cols = df_model.select_dtypes(
    include="object",
    
).columns

/var/folders/rf/55f17gkd0fs1mt6d7fkb_x340000gn/T/ipykernel_27137/1007304183.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df_model.select_dtypes(

In [14]:
encoder={}

In [15]:
for col in cat_cols:
    
    le=LabelEncoder()
    
    df_model[col]=le.fit_transform(
        df_model[col]
    )
    
    encoder[col]=le

In [16]:
features=[

"Age",
"Income",
"Tenure",

"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",

"LastPurchaseDays",

"WebsiteVisits",
"AppUsageMinutes",
"LoginFrequency",

"WishlistCount",

"CartAbandonmentRate",

"EmailOpenRate",

"MarketingClicks",

"SatisfactionScore",

"Rating",

"SupportCalls",

"Complaints",

"Reviews",

"CustomerHealthScore"

]

In [17]:
X=df_model[features]


X.shape

(50000, 21)

In [18]:
print("NaN in X before scaling:", X.isnull().sum().sum())

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

print("NaN in X_scaled:", np.isnan(X_scaled).sum())

NaN in X before scaling: 0
NaN in X_scaled: 0

In [19]:
np.isnan(X_scaled).sum()

np.int64(0)

In [20]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


scores={}

In [21]:
np.isnan(X_scaled).sum()

np.int64(0)

In [22]:
len(df)

50000

In [25]:
from sklearn.cluster import KMeans

In [26]:
from sklearn.cluster import KMeans

# Model
final_model = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=100
)


# Train
clusters = final_model.fit_predict(X_scaled)


# Add cluster
df.loc[:, "Customer_Segment"] = clusters


print(df["Customer_Segment"].value_counts())

Customer_Segment
1    42467
0     7533
Name: count, dtype: int64

In [27]:
final_model=KMeans(
    n_clusters=2,
    random_state=42,
    n_init=100
)


clusters=final_model.fit_predict(
    X_scaled
)


df["Customer_Segment"]=clusters

In [28]:
df["Customer_Segment"].value_counts()

Customer_Segment
1    42467
0     7533
Name: count, dtype: int64

In [29]:
segment_profile=df.groupby(
"Customer_Segment"
)[features].mean()


segment_profile

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.809239,196536.554432,3.526886,49318.403839,120.456392,494.864545,19.121333,14.424665,188.957786,3272.378734,...,85.933007,17.465992,74.905955,120.342626,90.099960,4.503988,1.504049,0.507766,60.504594,73.438484
1,41.901547,59097.890534,3.507384,5133.504676,30.112464,232.508753,4.647656,91.092024,57.944639,741.337980,...,33.212685,56.661038,40.120365,38.485365,61.674147,3.083505,6.450208,3.743825,16.269578,27.534076

In [30]:
segment_names={

0:"Premium Loyal Customers",

1:"Regular Customers",

2:"At Risk Customers"

}


df["Segment_Name"]=df[
"Customer_Segment"
].map(segment_names)

In [31]:
import joblib


joblib.dump(
    final_model,
    "customer_segmentation.pkl"
)


joblib.dump(
    scaler,
    "segmentation_scaler.pkl"
)

['segmentation_scaler.pkl']

In [32]:
new_customer=pd.DataFrame({

"Age":[45],
"Income":[85000],
"Tenure":[5],
"TotalSpend":[12000],
"TotalTransactions":[60],
"AverageOrderValue":[200],
"PurchaseFrequency":[8],
"LastPurchaseDays":[20],
"WebsiteVisits":[50],
"AppUsageMinutes":[300],
"LoginFrequency":[40],
"WishlistCount":[20],
"CartAbandonmentRate":[20],
"EmailOpenRate":[70],
"MarketingClicks":[50],
"SatisfactionScore":[85],
"Rating":[4.5],
"SupportCalls":[1],
"Complaints":[0],
"Reviews":[40],
"CustomerHealthScore":[80]

})


scaled=scaler.transform(
new_customer
)


prediction=final_model.predict(
scaled
)


print(
"Customer Segment:",
prediction[0]
)

Customer Segment: 1

In [33]:
import pandas as pd

new_customer = pd.DataFrame({

    "Age":[45],
    "Gender":[0],
    "Income":[85000],
    "Location":[5],
    "Membership":[3],
    "Tenure":[5],

    "TotalSpend":[12000],
    "TotalTransactions":[60],
    "AverageOrderValue":[200],
    "PurchaseFrequency":[8],

    "LastPurchaseDays":[20],

    "PreferredCategory":[2],

    "WebsiteVisits":[50],
    "AppUsageMinutes":[300],
    "LoginFrequency":[40],

    "WishlistCount":[20],

    "CartAbandonmentRate":[20],
    "EmailOpenRate":[70],

    "MarketingClicks":[50],

    "SatisfactionScore":[85],
    "Rating":[4.5],

    "SupportCalls":[1],
    "Complaints":[0],

    "Reviews":[40],

    "CustomerHealthScore":[80]

})


new_customer

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
0,45,0,85000,5,3,5,12000,60,200,8,...,20,20,70,50,85,4.5,1,0,40,80

In [34]:
new_customer.columns.equals(X.columns)

False

In [35]:
print("Training columns:")
print(X.columns.tolist())


print("\nTesting columns:")
print(new_customer.columns.tolist())

Training columns:
['Age', 'Income', 'Tenure', 'TotalSpend', 'TotalTransactions', 'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays', 'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore']

Testing columns:
['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure', 'TotalSpend', 'TotalTransactions', 'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays', 'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore']

In [36]:
remove_test_cols = [
    "Gender",
    "Location",
    "Membership",
    "PreferredCategory"
]


new_customer = new_customer.drop(
    columns=remove_test_cols
)

In [37]:
new_customer = new_customer[X.columns]

In [38]:
new_customer.columns.equals(X.columns)

True

In [39]:
new_scaled = scaler.transform(
    new_customer
)


prediction = final_model.predict(
    new_scaled
)


print(
    "Customer Segment:",
    prediction[0]
)

Customer Segment: 1

In [40]:
segment_analysis = df.groupby(
    "Customer_Segment"
)[X.columns].mean()

segment_analysis

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.809239,196536.554432,3.526886,49318.403839,120.456392,494.864545,19.121333,14.424665,188.957786,3272.378734,...,85.933007,17.465992,74.905955,120.342626,90.099960,4.503988,1.504049,0.507766,60.504594,73.438484
1,41.901547,59097.890534,3.507384,5133.504676,30.112464,232.508753,4.647656,91.092024,57.944639,741.337980,...,33.212685,56.661038,40.120365,38.485365,61.674147,3.083505,6.450208,3.743825,16.269578,27.534076

In [41]:
segment_analysis = df.groupby(
    "Customer_Segment"
)[X.columns].mean()

segment_analysis

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.809239,196536.554432,3.526886,49318.403839,120.456392,494.864545,19.121333,14.424665,188.957786,3272.378734,...,85.933007,17.465992,74.905955,120.342626,90.099960,4.503988,1.504049,0.507766,60.504594,73.438484
1,41.901547,59097.890534,3.507384,5133.504676,30.112464,232.508753,4.647656,91.092024,57.944639,741.337980,...,33.212685,56.661038,40.120365,38.485365,61.674147,3.083505,6.450208,3.743825,16.269578,27.534076

In [42]:
len(set(clusters))

2

In [43]:
X_scaled.mean(axis=0)

array([ 1.91278104e-16, -1.42392764e-16, -3.52287088e-16, -8.29913915e-17,
       -3.89377419e-17,  4.60431693e-17, -2.89901436e-17,  3.29691829e-17,
       -7.31859018e-17,  1.19086963e-16,  1.43529633e-17, -3.86535248e-17,
       -1.00897068e-16,  1.62856395e-16,  2.38742359e-17,  2.26521024e-16,
        3.74598130e-16, -5.45696821e-17,  2.27373675e-17, -5.94013727e-17,
       -1.19371180e-16])

In [44]:
X = df_model[features]

In [45]:
features = [
    "Age",
    "Income",
    "Tenure",
    "TotalSpend",
    "TotalTransactions",
    "AverageOrderValue",
    "PurchaseFrequency",
    "LastPurchaseDays",
    "WebsiteVisits",
    "AppUsageMinutes",
    "LoginFrequency",
    "WishlistCount",
    "CartAbandonmentRate",
    "EmailOpenRate",
    "MarketingClicks",
    "SatisfactionScore",
    "Rating",
    "SupportCalls",
    "Complaints",
    "Reviews",
    "CustomerHealthScore"
]


X = df[features]

In [46]:
df["Customer_Segment"].value_counts()

Customer_Segment
1    42467
0     7533
Name: count, dtype: int64

In [47]:
X.shape
X_scaled.shape
np.isnan(X_scaled).sum()

np.int64(0)

In [48]:
segment_analysis = df.groupby(
    "Customer_Segment"
).mean(numeric_only=True)

segment_analysis

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.809239,196536.554432,3.526886,49318.403839,120.456392,494.864545,19.121333,14.424665,188.957786,3272.378734,...,85.933007,17.465992,74.905955,120.342626,90.099960,4.503988,1.504049,0.507766,60.504594,73.438484
1,41.901547,59097.890534,3.507384,5133.504676,30.112464,232.508753,4.647656,91.092024,57.944639,741.337980,...,33.212685,56.661038,40.120365,38.485365,61.674147,3.083505,6.450208,3.743825,16.269578,27.534076

In [49]:
df_model["Customer_Segment"] = df["Customer_Segment"]
df_model["Segment_Name"] = df["Segment_Name"]

df_model[
[
"Customer_Segment",
"Segment_Name"
]
].head()

   Customer_Segment       Segment_Name
0                 1  Regular Customers
1                 1  Regular Customers
2                 1  Regular Customers
3                 1  Regular Customers
4                 1  Regular Customers

In [50]:
new_customer = pd.DataFrame({

"Age":[45],
"Income":[85000],
"Tenure":[5],
"TotalSpend":[12000],
"TotalTransactions":[60],
"AverageOrderValue":[200],
"PurchaseFrequency":[8],
"LastPurchaseDays":[20],
"WebsiteVisits":[100],
"AppUsageMinutes":[500],
"LoginFrequency":[80],
"WishlistCount":[20],
"CartAbandonmentRate":[10],
"EmailOpenRate":[70],
"MarketingClicks":[50],
"SatisfactionScore":[85],
"Rating":[4.5],
"SupportCalls":[1],
"Complaints":[0],
"Reviews":[40],
"CustomerHealthScore":[80]

})

In [51]:
new_scaled = scaler.transform(
    new_customer
)

In [52]:
prediction = final_model.predict(
    new_scaled
)


print(
    "Customer Segment:",
    prediction[0]
)

Customer Segment: 1

In [ ]:
# from sklearn.cluster import KMeans
# from sklearn.metrics import silhouette_score


# for k in range(2,8):

#     model = KMeans(
#         n_clusters=k,
#         random_state=42,
#         n_init=100
#     )

#     labels = model.fit_predict(X_scaled)

#     score = silhouette_score(
#         X_scaled,
#         labels
#     )

#     print(
#         f"K={k}: {score}"
#     )

In [58]:
from sklearn.metrics import silhouette_score

score = silhouette_score(
    X_scaled,
    clusters
)

print("Silhouette Score:", score)

Silhouette Score: 0.4676790971835295

In [59]:
segmentation_features = [

"Income",
"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",
"LastPurchaseDays",
"WebsiteVisits",
"LoginFrequency",
"CustomerHealthScore",
"SupportCalls",
"Complaints",
"SatisfactionScore"

]

In [60]:
df_model["Recency"] = 1 / (df["LastPurchaseDays"] + 1)

In [61]:
df_model["Frequency"] = df["TotalTransactions"]

In [62]:
df_model["Monetary"] = df["TotalSpend"]

In [65]:
df_model.columns

Index(['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure',
       'TotalSpend', 'TotalTransactions', 'AverageOrderValue',
       'PurchaseFrequency', 'LastPurchaseDays', 'PreferredCategory',
       'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount',
       'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks',
       'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews',
       'CustomerHealthScore', 'Customer_Segment', 'Segment_Name', 'Recency',
       'Frequency', 'Monetary'],
      dtype='str')

In [66]:
features = [
    "Income",
    "TotalSpend",
    "TotalTransactions",
    "AverageOrderValue",
    "PurchaseFrequency",
    "LastPurchaseDays",
    "WebsiteVisits",
    "AppUsageMinutes",
    "LoginFrequency",
    "CustomerHealthScore",
    "SatisfactionScore",
    "SupportCalls",
    "Complaints",

]


X = df_model[features]

In [67]:
import numpy as np


df_model["LogSpend"] = np.log1p(
    df["TotalSpend"]
)


df_model["LogIncome"] = np.log1p(
    df["Income"]
)

In [68]:
df_model.isnull().sum()

Age                       0
Gender                    0
Income                    0
Location                  0
Membership                0
Tenure                    0
TotalSpend                0
TotalTransactions         0
AverageOrderValue         0
PurchaseFrequency         0
LastPurchaseDays          0
PreferredCategory         0
WebsiteVisits             0
AppUsageMinutes           0
LoginFrequency            0
WishlistCount             0
CartAbandonmentRate       0
EmailOpenRate             0
MarketingClicks           0
SatisfactionScore         0
Rating                    0
SupportCalls              0
Complaints                0
Reviews                   0
CustomerHealthScore       0
Customer_Segment          0
Segment_Name              0
Recency                   0
Frequency                 0
Monetary                  0
LogSpend                  0
LogIncome              2236
dtype: int64

In [69]:
df_model["Income"].isnull().sum()

np.int64(0)

In [70]:
df_model["Income"] = df["Income"].fillna(
    df["Income"].median()
)

In [73]:
df_model.drop(
    columns=["LogIncome"],
    inplace=True,
    errors="ignore"
)

In [74]:
import numpy as np

df_model["LogIncome"] = np.log1p(
    df["Income"]
)

In [75]:
from sklearn.preprocessing import StandardScaler


X = df_model[features]


scaler = StandardScaler()


X_scaled = scaler.fit_transform(X)

In [78]:
X.isnull().sum().sort_values(ascending=False)

Income                 0
TotalSpend             0
TotalTransactions      0
AverageOrderValue      0
PurchaseFrequency      0
LastPurchaseDays       0
WebsiteVisits          0
AppUsageMinutes        0
LoginFrequency         0
CustomerHealthScore    0
SatisfactionScore      0
SupportCalls           0
Complaints             0
dtype: int64

In [79]:
import numpy as np

np.isnan(X_scaled).sum()

np.int64(0)

In [80]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [82]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


k4 = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=200
)


labels = k4.fit_predict(
    X_scaled
)


score = silhouette_score(
    X_scaled,
    labels
)


print(score)

0.3423977838756287

In [83]:
from sklearn.decomposition import PCA


pca = PCA(
    n_components=5
)


X_pca = pca.fit_transform(
    X_scaled
)

In [84]:
k4.fit_predict(X_pca)

array([1, 2, 3, ..., 3, 1, 2], shape=(50000,), dtype=int32)

In [85]:
df_model["Customer_Segment"] = labels


df_model["Customer_Segment"].value_counts()

Customer_Segment
2    19975
0    12821
1     9760
3     7444
Name: count, dtype: int64

In [87]:
segment_profile[[
"Income",
"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",
"LastPurchaseDays",
"CustomerHealthScore",
"SatisfactionScore",
"SupportCalls",
"Complaints"
]]

,Income,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,CustomerHealthScore,SatisfactionScore,SupportCalls,Complaints
Customer_Segment,,,,,,,,,,
0,196536.554432,49318.403839,120.456392,494.864545,19.121333,14.424665,73.438484,90.099960,1.504049,0.507766
1,59097.890534,5133.504676,30.112464,232.508753,4.647656,91.092024,27.534076,61.674147,6.450208,3.743825

In [89]:
numeric_df = df_model.select_dtypes(
    include="number"
)

segment_profile = numeric_df.groupby(
    "Customer_Segment"
).mean()

segment_profile

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore,Recency,Frequency,Monetary,LogSpend,LogIncome
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,36.306684,0.491615,34575.568020,9.539116,0.725060,3.528160,1678.672177,19.532798,112.480447,2.997114,...,3.233430,4.035723,2.031745,12.830122,23.904844,0.022062,19.532798,1678.672177,7.226108,10.350296
1,46.787705,0.495082,55590.119765,9.399385,1.323053,3.510519,2073.573253,9.925922,389.832211,2.000820,...,1.433361,17.651947,11.560963,5.112602,14.547633,0.004474,9.925922,2073.573253,7.393003,10.863771
2,43.144481,0.490013,77370.944842,9.479599,1.988786,3.489629,8913.881844,47.019825,232.889986,7.034193,...,3.840155,2.504681,1.008761,24.195394,36.316976,0.043930,47.019825,8913.881844,8.985853,11.232630
3,48.786405,0.489656,191630.461357,9.515986,2.702445,3.534867,49664.825152,120.856529,497.435807,19.203520,...,4.472676,1.503896,0.507792,58.476760,73.697098,0.133116,120.856529,49664.825152,10.693787,12.138664

In [90]:
df_model.dtypes

Age                      int64
Gender                   int64
Income                 float64
Location                 int64
Membership               int64
Tenure                 float64
TotalSpend             float64
TotalTransactions        int64
AverageOrderValue      float64
PurchaseFrequency        int64
LastPurchaseDays         int64
PreferredCategory        int64
WebsiteVisits            int64
AppUsageMinutes          int64
LoginFrequency           int64
WishlistCount          float64
CartAbandonmentRate    float64
EmailOpenRate          float64
MarketingClicks          int64
SatisfactionScore        int64
Rating                 float64
SupportCalls             int64
Complaints               int64
Reviews                float64
CustomerHealthScore    float64
Customer_Segment         int32
Segment_Name               str
Recency                float64
Frequency                int64
Monetary               float64
LogSpend               float64
LogIncome              float64
dtype: object

In [91]:
important_cols = [
    "Income",
    "TotalSpend",
    "TotalTransactions",
    "AverageOrderValue",
    "PurchaseFrequency",
    "LastPurchaseDays",
    "CustomerHealthScore",
    "SatisfactionScore",
    "SupportCalls",
    "Complaints"
]


segment_profile = df_model.groupby(
    "Customer_Segment"
)[important_cols].mean()


segment_profile

,Income,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,CustomerHealthScore,SatisfactionScore,SupportCalls,Complaints
Customer_Segment,,,,,,,,,,
0,34575.568020,1678.672177,19.532798,112.480447,2.997114,65.820919,23.904844,64.359488,4.035723,2.031745
1,55590.119765,2073.573253,9.925922,389.832211,2.000820,244.733811,14.547633,26.971414,17.651947,11.560963
2,77370.944842,8913.881844,47.019825,232.889986,7.034193,31.900926,36.316976,77.031339,2.504681,1.008761
3,191630.461357,49664.825152,120.856529,497.435807,19.203520,14.421413,73.697098,90.105320,1.503896,0.507792

In [92]:
segment_mapping = {
    0: "Low Value Customers",
    1: "At Risk Customers",
    2: "Regular Loyal Customers",
    3: "VIP Customers"
}

In [93]:
df_model["Segment_Name"] = df_model["Customer_Segment"].map(
    segment_mapping
)

In [94]:
df_model[
[
"Customer_Segment",
"Segment_Name"
]
].head()

   Customer_Segment             Segment_Name
0                 2  Regular Loyal Customers
1                 1        At Risk Customers
2                 0      Low Value Customers
3                 0      Low Value Customers
4                 2  Regular Loyal Customers

In [103]:
import pickle


with open("customer_segmentation_model.pkl","wb") as f:
    pickle.dump(df_model,f)



with open("segmentation_scaler.pkl","wb") as f:
    pickle.dump(scaler,f)