In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Step 1: Original dataset load

In [2]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM-AI/data/raw/customer .csv")

In [5]:
df.shape

(50000, 28)

In [7]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Location', 'Membership',
       'RegistrationDate', 'Tenure', 'TotalSpend', 'TotalTransactions',
       'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
       'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
       'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
       'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating',
       'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore',
       'ChurnRisk'],
      dtype='str')

In [8]:
remove_cols =[ 
            "CustomerID",
            "RegistrationDate",
            "ChurnRisk"
             ]

In [9]:
df_model = df.drop(
    columns=remove_cols,
    errors='ignore'
)

In [11]:
df_model.head()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
0,54,Female,72543.43,NJ,Gold,6.81,4389.80,30,146.33,3,...,14.0,48.5,65.6,79,65,3.2,0,2,8.0,31.8
1,42,Male,78149.18,AZ,Silver,5.14,706.89,2,353.45,2,...,7.0,87.9,23.4,0,1,0.0,5,18,0.0,11.6
2,24,Female,48635.85,MD,Free,0.37,2935.65,20,146.78,3,...,50.0,87.8,62.3,24,55,2.8,7,1,23.0,18.2
3,31,Male,19935.67,GA,Free,1.11,1410.68,32,44.08,2,...,30.0,73.0,32.0,23,74,3.7,5,3,3.0,21.0
4,45,Female,83500.57,AZ,Silver,6.80,4352.92,69,63.09,5,...,19.0,25.5,59.0,38,77,3.8,4,2,17.0,36.4

In [12]:
df_model.isnull().sum()

Age                       0
Gender                    0
Income                 2236
Location                  0
Membership                0
Tenure                    0
TotalSpend                0
TotalTransactions         0
AverageOrderValue         0
PurchaseFrequency         0
LastPurchaseDays          0
PreferredCategory         0
WebsiteVisits             0
AppUsageMinutes           0
LoginFrequency            0
WishlistCount          1110
CartAbandonmentRate    1253
EmailOpenRate          2402
MarketingClicks           0
SatisfactionScore         0
Rating                 1824
SupportCalls              0
Complaints                0
Reviews                2375
CustomerHealthScore       0
dtype: int64

In [18]:
num_cols = df_model.select_dtypes(
    include=np.number
).columns

In [19]:
for col in num_cols:
    df_model[col] = df_model[col].fillna(
        df_model[col].median()
    )

In [21]:
df_model.isnull().sum()

Age                    0
Gender                 0
Income                 0
Location               0
Membership             0
Tenure                 0
TotalSpend             0
TotalTransactions      0
AverageOrderValue      0
PurchaseFrequency      0
LastPurchaseDays       0
PreferredCategory      0
WebsiteVisits          0
AppUsageMinutes        0
LoginFrequency         0
WishlistCount          0
CartAbandonmentRate    0
EmailOpenRate          0
MarketingClicks        0
SatisfactionScore      0
Rating                 0
SupportCalls           0
Complaints             0
Reviews                0
CustomerHealthScore    0
dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
cat_cols = df_model.select_dtypes(
    include="object",
    
).columns

/var/folders/rf/55f17gkd0fs1mt6d7fkb_x340000gn/T/ipykernel_20623/1007304183.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df_model.select_dtypes(

In [26]:
encoder={}

In [28]:
for col in cat_cols:
    
    le=LabelEncoder()
    
    df_model[col]=le.fit_transform(
        df_model[col]
    )
    
    encoder[col]=le

In [29]:
features=[

"Age",
"Income",
"Tenure",

"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",

"LastPurchaseDays",

"WebsiteVisits",
"AppUsageMinutes",
"LoginFrequency",

"WishlistCount",

"CartAbandonmentRate",

"EmailOpenRate",

"MarketingClicks",

"SatisfactionScore",

"Rating",

"SupportCalls",

"Complaints",

"Reviews",

"CustomerHealthScore"

]

In [30]:
X=df_model[features]


X.shape

(50000, 21)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [32]:
np.isnan(X_scaled).sum()

np.int64(0)

In [33]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


scores={}

In [70]:
np.isnan(X_scaled).sum()

np.int64(0)

In [71]:
len(df)

50000

In [72]:
len(clusters)

50000

In [73]:
from sklearn.cluster import KMeans

In [74]:
from sklearn.cluster import KMeans

# Model
final_model = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=100
)


# Train
clusters = final_model.fit_predict(X_scaled)


# Add cluster
df.loc[:, "Customer_Segment"] = clusters


print(df["Customer_Segment"].value_counts())

Customer_Segment
0    50000
Name: count, dtype: int64

/Users/aashishmewada/Desktop/PRISM AI/.venv/lib/python3.14/site-packages/sklearn/base.py:1403: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)

In [54]:
final_model=KMeans(
    n_clusters=2,
    random_state=42,
    n_init=100
)


clusters=final_model.fit_predict(
    X_scaled
)


df["Customer_Segment"]=clusters

/Users/aashishmewada/Desktop/PRISM AI/.venv/lib/python3.14/site-packages/sklearn/base.py:1403: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)

In [55]:
df["Customer_Segment"].value_counts()

Customer_Segment
0    50000
Name: count, dtype: int64

In [56]:
segment_profile=df.groupby(
"Customer_Segment"
)[features].mean()


segment_profile

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,42.94226,79835.694125,3.510322,11790.401584,43.72368,272.035276,6.82826,79.54132,77.68308,1122.66458,...,41.148231,50.743227,45.361078,50.81798,65.95678,3.297922,5.70502,3.25628,22.942215,34.450034

In [57]:
segment_names={

0:"Premium Loyal Customers",

1:"Regular Customers",

2:"At Risk Customers"

}


df["Segment_Name"]=df[
"Customer_Segment"
].map(segment_names)

In [58]:
import joblib


joblib.dump(
    final_model,
    "customer_segmentation.pkl"
)


joblib.dump(
    scaler,
    "segmentation_scaler.pkl"
)

['segmentation_scaler.pkl']

In [59]:
new_customer=pd.DataFrame({

"Age":[45],
"Income":[85000],
"Tenure":[5],
"TotalSpend":[12000],
"TotalTransactions":[60],
"AverageOrderValue":[200],
"PurchaseFrequency":[8],
"LastPurchaseDays":[20],
"WebsiteVisits":[50],
"AppUsageMinutes":[300],
"LoginFrequency":[40],
"WishlistCount":[20],
"CartAbandonmentRate":[20],
"EmailOpenRate":[70],
"MarketingClicks":[50],
"SatisfactionScore":[85],
"Rating":[4.5],
"SupportCalls":[1],
"Complaints":[0],
"Reviews":[40],
"CustomerHealthScore":[80]

})


scaled=scaler.transform(
new_customer
)


prediction=final_model.predict(
scaled
)


print(
"Customer Segment:",
prediction[0]
)

Customer Segment: 0

In [60]:
import pandas as pd

new_customer = pd.DataFrame({

    "Age":[45],
    "Gender":[0],
    "Income":[85000],
    "Location":[5],
    "Membership":[3],
    "Tenure":[5],

    "TotalSpend":[12000],
    "TotalTransactions":[60],
    "AverageOrderValue":[200],
    "PurchaseFrequency":[8],

    "LastPurchaseDays":[20],

    "PreferredCategory":[2],

    "WebsiteVisits":[50],
    "AppUsageMinutes":[300],
    "LoginFrequency":[40],

    "WishlistCount":[20],

    "CartAbandonmentRate":[20],
    "EmailOpenRate":[70],

    "MarketingClicks":[50],

    "SatisfactionScore":[85],
    "Rating":[4.5],

    "SupportCalls":[1],
    "Complaints":[0],

    "Reviews":[40],

    "CustomerHealthScore":[80]

})


new_customer

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
0,45,0,85000,5,3,5,12000,60,200,8,...,20,20,70,50,85,4.5,1,0,40,80

In [61]:
new_customer.columns.equals(X.columns)

False

In [62]:
print("Training columns:")
print(X.columns.tolist())


print("\nTesting columns:")
print(new_customer.columns.tolist())

Training columns:
['Age', 'Income', 'Tenure', 'TotalSpend', 'TotalTransactions', 'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays', 'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore']

Testing columns:
['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure', 'TotalSpend', 'TotalTransactions', 'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays', 'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore']

In [63]:
remove_test_cols = [
    "Gender",
    "Location",
    "Membership",
    "PreferredCategory"
]


new_customer = new_customer.drop(
    columns=remove_test_cols
)

In [64]:
new_customer = new_customer[X.columns]

In [65]:
new_customer.columns.equals(X.columns)

True

In [66]:
new_scaled = scaler.transform(
    new_customer
)


prediction = final_model.predict(
    new_scaled
)


print(
    "Customer Segment:",
    prediction[0]
)

Customer Segment: 0

In [67]:
segment_analysis = df.groupby(
    "Customer_Segment"
)[X.columns].mean()

segment_analysis

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,42.94226,79835.694125,3.510322,11790.401584,43.72368,272.035276,6.82826,79.54132,77.68308,1122.66458,...,41.148231,50.743227,45.361078,50.81798,65.95678,3.297922,5.70502,3.25628,22.942215,34.450034

In [68]:
segment_analysis = df.groupby(
    "Customer_Segment"
)[X.columns].mean()

segment_analysis

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,42.94226,79835.694125,3.510322,11790.401584,43.72368,272.035276,6.82826,79.54132,77.68308,1122.66458,...,41.148231,50.743227,45.361078,50.81798,65.95678,3.297922,5.70502,3.25628,22.942215,34.450034

In [69]:
len(set(clusters))

1

In [75]:
X_scaled.mean(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])

In [76]:
X = df_model[features]

In [77]:
features = [
    "Age",
    "Income",
    "Tenure",
    "TotalSpend",
    "TotalTransactions",
    "AverageOrderValue",
    "PurchaseFrequency",
    "LastPurchaseDays",
    "WebsiteVisits",
    "AppUsageMinutes",
    "LoginFrequency",
    "WishlistCount",
    "CartAbandonmentRate",
    "EmailOpenRate",
    "MarketingClicks",
    "SatisfactionScore",
    "Rating",
    "SupportCalls",
    "Complaints",
    "Reviews",
    "CustomerHealthScore"
]


X = df[features]

In [78]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [79]:
X_scaled.shape

(50000, 21)

In [80]:
from sklearn.cluster import KMeans

final_model = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=100
)


clusters = final_model.fit_predict(X_scaled)


df["Customer_Segment"] = clusters

ValueError: Input X contains NaN.
KMeans does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [81]:
type(X_scaled)

numpy.ndarray

In [82]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_clean = imputer.fit_transform(X)

In [83]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_clean)

In [84]:
from sklearn.cluster import KMeans

final_model = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=100
)

clusters = final_model.fit_predict(X_scaled)

df["Customer_Segment"] = clusters

In [85]:
df["Customer_Segment"].value_counts()

Customer_Segment
1    42467
0     7533
Name: count, dtype: int64

In [86]:
X.shape
X_scaled.shape
np.isnan(X_scaled).sum()

np.int64(0)

In [87]:
segment_analysis = df.groupby(
    "Customer_Segment"
).mean(numeric_only=True)

segment_analysis

,Age,Income,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,LastPurchaseDays,WebsiteVisits,AppUsageMinutes,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.809239,196536.554432,3.526886,49318.403839,120.456392,494.864545,19.121333,14.424665,188.957786,3272.378734,...,85.933007,17.465992,74.905955,120.342626,90.099960,4.503988,1.504049,0.507766,60.504594,73.438484
1,41.901547,59097.890534,3.507384,5133.504676,30.112464,232.508753,4.647656,91.092024,57.944639,741.337980,...,33.212685,56.661038,40.120365,38.485365,61.674147,3.083505,6.450208,3.743825,16.269578,27.534076

In [89]:
df_model[
[
"Customer_Segment",
"Customer_Segment_Name"
]
].head()

KeyError: "None of [Index(['Customer_Segment', 'Customer_Segment_Name'], dtype='str')] are in the [columns]"