In [77]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import joblib

In [78]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM-AI/data/raw/customer .csv")

In [79]:
df.head()

,CustomerID,Age,Gender,Income,Location,Membership,RegistrationDate,Tenure,TotalSpend,TotalTransactions,...,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore,ChurnRisk
0,CUST000001,54,Female,72543.43,NJ,Gold,2020-03-10,6.81,4389.80,30,...,48.5,65.6,79,65,3.2,0,2,8.0,31.8,High
1,CUST000002,42,Male,78149.18,AZ,Silver,2021-11-10,5.14,706.89,2,...,87.9,23.4,0,1,0.0,5,18,0.0,11.6,High
2,CUST000003,24,Female,48635.85,MD,Free,2026-08-18,0.37,2935.65,20,...,87.8,62.3,24,55,2.8,7,1,23.0,18.2,High
3,CUST000004,31,Male,19935.67,GA,Free,2025-11-20,1.11,1410.68,32,...,73.0,32.0,23,74,3.7,5,3,3.0,21.0,High
4,CUST000005,45,Female,83500.57,AZ,Silver,2020-03-11,6.80,4352.92,69,...,25.5,59.0,38,77,3.8,4,2,17.0,36.4,High

In [82]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Location', 'Membership',
       'RegistrationDate', 'Tenure', 'TotalSpend', 'TotalTransactions',
       'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
       'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
       'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
       'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating',
       'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore',
       'ChurnRisk'],
      dtype='str')

In [83]:
df.isnull().sum()

CustomerID                0
Age                       0
Gender                    0
Income                 2236
Location                  0
Membership                0
RegistrationDate          0
Tenure                    0
TotalSpend                0
TotalTransactions         0
AverageOrderValue         0
PurchaseFrequency         0
LastPurchaseDays          0
PreferredCategory         0
WebsiteVisits             0
AppUsageMinutes           0
LoginFrequency            0
WishlistCount          1110
CartAbandonmentRate    1253
EmailOpenRate          2402
MarketingClicks           0
SatisfactionScore         0
Rating                 1824
SupportCalls              0
Complaints                0
Reviews                2375
CustomerHealthScore       0
ChurnRisk                 0
dtype: int64

In [84]:
numeric_cols = df.select_dtypes(
    include=["int64","float64"]
).columns


imputer = SimpleImputer(
    strategy="median"
)


df[numeric_cols] = imputer.fit_transform(
    df[numeric_cols]
)

In [85]:
df.isnull().sum()

CustomerID             0
Age                    0
Gender                 0
Income                 0
Location               0
Membership             0
RegistrationDate       0
Tenure                 0
TotalSpend             0
TotalTransactions      0
AverageOrderValue      0
PurchaseFrequency      0
LastPurchaseDays       0
PreferredCategory      0
WebsiteVisits          0
AppUsageMinutes        0
LoginFrequency         0
WishlistCount          0
CartAbandonmentRate    0
EmailOpenRate          0
MarketingClicks        0
SatisfactionScore      0
Rating                 0
SupportCalls           0
Complaints             0
Reviews                0
CustomerHealthScore    0
ChurnRisk              0
dtype: int64

In [86]:
df.drop(
    [
    "CustomerID",
    "RegistrationDate",
    "ChurnRisk"
    ],
    axis=1,
    inplace=True
)

In [87]:
df.select_dtypes(
    include="object"
).columns

/var/folders/rf/55f17gkd0fs1mt6d7fkb_x340000gn/T/ipykernel_14810/3038113494.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(

Index(['Gender', 'Location', 'Membership', 'PreferredCategory'], dtype='str')

In [88]:
encoder = LabelEncoder()


for col in df.select_dtypes(include="object").columns:
    
    df[col] = encoder.fit_transform(
        df[col]
    )

/var/folders/rf/55f17gkd0fs1mt6d7fkb_x340000gn/T/ipykernel_14810/2219365825.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [89]:
df.head()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
0,54.0,0,72543.43,12,2,6.81,4389.80,30.0,146.33,3.0,...,14.0,48.5,65.6,79.0,65.0,3.2,0.0,2.0,8.0,31.8
1,42.0,1,78149.18,0,4,5.14,706.89,2.0,353.45,2.0,...,7.0,87.9,23.4,0.0,1.0,0.0,5.0,18.0,0.0,11.6
2,24.0,0,48635.85,8,1,0.37,2935.65,20.0,146.78,3.0,...,50.0,87.8,62.3,24.0,55.0,2.8,7.0,1.0,23.0,18.2
3,31.0,1,19935.67,4,1,1.11,1410.68,32.0,44.08,2.0,...,30.0,73.0,32.0,23.0,74.0,3.7,5.0,3.0,3.0,21.0
4,45.0,0,83500.57,0,4,6.80,4352.92,69.0,63.09,5.0,...,19.0,25.5,59.0,38.0,77.0,3.8,4.0,2.0,17.0,36.4

In [90]:
df.dtypes

Age                    float64
Gender                   int64
Income                 float64
Location                 int64
Membership               int64
Tenure                 float64
TotalSpend             float64
TotalTransactions      float64
AverageOrderValue      float64
PurchaseFrequency      float64
LastPurchaseDays       float64
PreferredCategory        int64
WebsiteVisits          float64
AppUsageMinutes        float64
LoginFrequency         float64
WishlistCount          float64
CartAbandonmentRate    float64
EmailOpenRate          float64
MarketingClicks        float64
SatisfactionScore      float64
Rating                 float64
SupportCalls           float64
Complaints             float64
Reviews                float64
CustomerHealthScore    float64
dtype: object

In [104]:
df["CustomerValueScore"] = (
    df["TotalSpend"] *
    df["PurchaseFrequency"]
)

In [106]:
df["EngagementScore"] = (
    df["WebsiteVisits"]
    +
    df["LoginFrequency"]
    +
    df["AppUsageMinutes"]/10
)

In [107]:
df["LoyaltyScore"] = (
    df["Tenure"]
    +
    df["TotalTransactions"]/10
)

In [108]:
df["SatisfactionIndex"] = (
    df["SatisfactionScore"]
    +
    df["Rating"]*20
    -
    df["Complaints"]*5
)

In [109]:
df["PurchaseIntensity"] = (
    df["TotalTransactions"]
    /
    (df["Tenure"]+1)
)

In [114]:
df.columns

Index(['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure',
       'TotalSpend', 'TotalTransactions', 'AverageOrderValue',
       'PurchaseFrequency', 'LastPurchaseDays', 'PreferredCategory',
       'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount',
       'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks',
       'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews',
       'CustomerHealthScore', 'Customer_Segment', 'CustomerValueScore',
       'EngagementScore', 'LoyaltyScore', 'SatisfactionIndex',
       'PurchaseIntensity'],
      dtype='str')

In [115]:
from sklearn.preprocessing import LabelEncoder


cat_cols = df.select_dtypes(
    include="object"
).columns


encoder = LabelEncoder()


for col in cat_cols:
    df[col] = encoder.fit_transform(
        df[col]
    )

In [116]:
features = [

"Income",

"TotalSpend",
"TotalTransactions",
"AverageOrderValue",

"PurchaseFrequency",
"LastPurchaseDays",

"WebsiteVisits",
"AppUsageMinutes",
"LoginFrequency",

"SatisfactionScore",
"Rating",
"Complaints",
"SupportCalls",

"CustomerValueScore",
"EngagementScore",
"LoyaltyScore",
"SatisfactionIndex",
"PurchaseIntensity"

]

In [117]:
from sklearn.preprocessing import StandardScaler


X = df[features]


scaler = StandardScaler()


X_scaled = scaler.fit_transform(
    X
)

df["CustomerValueScore"] = (
    df["TotalSpend"] *
    df["PurchaseFrequency"]
)

In [118]:
scores = []


for k in range(2,11):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=20
    )


    labels = kmeans.fit_predict(
        X_scaled
    )


    score = silhouette_score(
        X_scaled,
        labels
    )


    scores.append(score)


    print(
        f"K={k} : {score}"
    )

K=2 : 0.5268511211316158
K=3 : 0.5107173247333862
K=4 : 0.3167157020001861
K=5 : 0.30116222805901094
K=6 : 0.3080205458021921
K=7 : 0.30935884860845836
K=8 : 0.2706019584294255
K=9 : 0.22227033233976065
K=10 : 0.22000724066277005

In [135]:
kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=30
)

clusters = kmeans.fit_predict(
    X_scaled
)

df["Customer_Segment"] = clusters

In [136]:
df["Customer_Segment"].value_counts()

Customer_Segment
0    32602
1     9911
2     7487
Name: count, dtype: int64

In [137]:
segment_analysis = df.groupby(
    "Customer_Segment"
).mean(numeric_only=True)


segment_analysis[
[
"Income",
"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",
"CustomerHealthScore",
"CustomerValueScore",
"EngagementScore",
"SatisfactionIndex",
"PurchaseIntensity"
]
]

,Income,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,CustomerHealthScore,CustomerValueScore,EngagementScore,SatisfactionIndex,PurchaseIntensity
Customer_Segment,,,,,,,,,,
0,60605.987549,6084.760377,36.289767,185.708100,5.462855,31.502641,40171.989098,209.484084,137.410006,10.779958
1,55594.626050,2071.171081,9.958632,386.954819,2.001715,14.597034,4157.001835,33.909838,-1.259207,2.920558
2,191125.946199,49501.448483,120.791372,495.819307,19.163083,73.565033,949513.919005,642.402618,177.020168,35.576513

In [123]:
df.head()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,SupportCalls,Complaints,Reviews,CustomerHealthScore,Customer_Segment,CustomerValueScore,EngagementScore,LoyaltyScore,SatisfactionIndex,PurchaseIntensity
0,54.0,0,72543.43,12,2,6.81,4389.80,30.0,146.33,3.0,...,0.0,2.0,8.0,31.8,1,13169.40,245.0,9.81,119.0,3.841229
1,42.0,1,78149.18,0,4,5.14,706.89,2.0,353.45,2.0,...,5.0,18.0,0.0,11.6,1,1413.78,40.0,5.34,-89.0,0.325733
2,24.0,0,48635.85,8,1,0.37,2935.65,20.0,146.78,3.0,...,7.0,1.0,23.0,18.2,1,8806.95,131.1,2.37,106.0,14.598540
3,31.0,1,19935.67,4,1,1.11,1410.68,32.0,44.08,2.0,...,5.0,3.0,3.0,21.0,1,2821.36,126.4,4.31,133.0,15.165877
4,45.0,0,83500.57,0,4,6.80,4352.92,69.0,63.09,5.0,...,4.0,2.0,17.0,36.4,1,21764.60,305.3,13.70,143.0,8.846154

In [124]:
df.tail()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,SupportCalls,Complaints,Reviews,CustomerHealthScore,Customer_Segment,CustomerValueScore,EngagementScore,LoyaltyScore,SatisfactionIndex,PurchaseIntensity
49995,34.0,0,19966.08,19,0,5.19,2303.66,13.0,177.20,3.0,...,2.0,0.0,13.0,26.7,1,6910.98,100.5,6.49,128.0,2.100162
49996,30.0,1,56753.59,19,0,6.51,2612.76,28.0,93.31,8.0,...,3.0,1.0,28.0,37.4,1,20902.08,330.9,9.31,140.0,3.728362
49997,50.0,1,34356.15,18,1,0.14,2734.62,22.0,124.30,1.0,...,4.0,4.0,2.0,20.2,1,2734.62,122.8,2.34,133.0,19.298246
49998,34.0,0,84115.25,14,0,3.72,13285.26,74.0,179.53,3.0,...,5.0,2.0,8.0,35.7,1,39855.78,213.6,11.12,158.0,15.677966
49999,48.0,0,35473.37,5,4,2.00,2735.89,6.0,455.98,2.0,...,10.0,20.0,4.0,16.2,1,5471.78,11.5,2.60,-5.0,2.000000

In [125]:
df.groupby(
    "Customer_Segment"
).mean()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore,CustomerValueScore,EngagementScore,LoyaltyScore,SatisfactionIndex,PurchaseIntensity
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.802738,0.489034,190865.613076,9.500332,2.701449,3.524793,49376.159953,120.536887,495.390901,19.131995,...,4.472724,1.503655,0.508574,58.466968,73.462621,946281.884636,641.442869,15.578482,177.013425,35.506984
1,41.904325,0.491772,59372.194291,9.481837,1.453234,3.507759,5133.677705,30.119476,232.477295,4.649175,...,3.102827,6.449114,3.742920,16.318266,27.540608,31570.481137,168.321073,6.519706,105.022459,8.937452

In [138]:
df_original = df.copy()

In [140]:
remove_cols = [
    "CustomerID",
    "RegistrationDate",
    "ChurnRisk"
]

df_model = df.drop(
    columns=remove_cols,
    errors="ignore"
)

In [141]:
for col in remove_cols:
    print(col, col in df.columns)

CustomerID False
RegistrationDate False
ChurnRisk False

In [142]:
df_model = df.copy()

df_model = df_model.drop(
    columns=["CustomerID"],
    errors="ignore"
)

df_model.head()

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,SupportCalls,Complaints,Reviews,CustomerHealthScore,Customer_Segment,CustomerValueScore,EngagementScore,LoyaltyScore,SatisfactionIndex,PurchaseIntensity
0,54.0,0,72543.43,12,2,6.81,4389.80,30.0,146.33,3.0,...,0.0,2.0,8.0,31.8,0,13169.40,245.0,9.81,119.0,3.841229
1,42.0,1,78149.18,0,4,5.14,706.89,2.0,353.45,2.0,...,5.0,18.0,0.0,11.6,1,1413.78,40.0,5.34,-89.0,0.325733
2,24.0,0,48635.85,8,1,0.37,2935.65,20.0,146.78,3.0,...,7.0,1.0,23.0,18.2,0,8806.95,131.1,2.37,106.0,14.598540
3,31.0,1,19935.67,4,1,1.11,1410.68,32.0,44.08,2.0,...,5.0,3.0,3.0,21.0,0,2821.36,126.4,4.31,133.0,15.165877
4,45.0,0,83500.57,0,4,6.80,4352.92,69.0,63.09,5.0,...,4.0,2.0,17.0,36.4,0,21764.60,305.3,13.70,143.0,8.846154

In [143]:
df_model.dtypes

Age                    float64
Gender                   int64
Income                 float64
Location                 int64
Membership               int64
Tenure                 float64
TotalSpend             float64
TotalTransactions      float64
AverageOrderValue      float64
PurchaseFrequency      float64
LastPurchaseDays       float64
PreferredCategory        int64
WebsiteVisits          float64
AppUsageMinutes        float64
LoginFrequency         float64
WishlistCount          float64
CartAbandonmentRate    float64
EmailOpenRate          float64
MarketingClicks        float64
SatisfactionScore      float64
Rating                 float64
SupportCalls           float64
Complaints             float64
Reviews                float64
CustomerHealthScore    float64
Customer_Segment         int32
CustomerValueScore     float64
EngagementScore        float64
LoyaltyScore           float64
SatisfactionIndex      float64
PurchaseIntensity      float64
dtype: object

In [144]:
df_model.isnull().sum().sort_values(ascending=False).head(20)

Age                    0
CartAbandonmentRate    0
SatisfactionIndex      0
LoyaltyScore           0
EngagementScore        0
CustomerValueScore     0
Customer_Segment       0
CustomerHealthScore    0
Reviews                0
Complaints             0
SupportCalls           0
Rating                 0
SatisfactionScore      0
MarketingClicks        0
EmailOpenRate          0
WishlistCount          0
Gender                 0
LoginFrequency         0
AppUsageMinutes        0
WebsiteVisits          0
dtype: int64

In [145]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

df_model[:] = imputer.fit_transform(df_model)

In [146]:
df_model.isnull().sum().sum()

np.int64(0)

In [147]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_scaled = scaler.fit_transform(df_model)

In [148]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


scores = {}

for k in range(2,8):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=50
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    scores[k] = score

    print(
        f"K={k} : {score}"
    )

K=2 : 0.6297469377642151
K=3 : 0.4695121003389785
K=4 : 0.47852779181292615
K=5 : 0.25261458157376454
K=6 : 0.24732313382166177
K=7 : 0.2543070878098018

In [149]:
kmeans = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=50
)


df_model["Customer_Segment"] = kmeans.fit_predict(
    X_scaled
)

In [150]:
df_model["Customer_Segment"].value_counts()

Customer_Segment
0    43633
1     6367
Name: count, dtype: int64

In [151]:
segment_analysis = df_model.groupby(
    "Customer_Segment"
).mean()

segment_analysis

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore,CustomerValueScore,EngagementScore,LoyaltyScore,SatisfactionIndex,PurchaseIntensity
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,42.101277,0.492403,62629.073846,9.468957,1.486467,3.509664,5576.703893,32.346137,232.607565,4.897417,...,3.138909,6.318314,3.657988,17.401141,28.347792,3.822974e+04,180.554858,6.744278,106.920473,9.552906
1,48.705513,0.484215,192420.343163,9.591959,2.700330,3.514828,54372.822087,121.693890,542.233067,20.060311,...,4.474179,1.502120,0.503377,58.698602,76.268651,1.066722e+06,643.505387,15.684217,177.077116,36.113281

In [152]:
df_model.drop(
[
"Customer_Segment",
"CustomerValueScore"
],
axis=1,
inplace=True
)

In [153]:
df_model["SatisfactionIndex"].describe()

count    50000.00000
mean       115.85422
std         65.18177
min        -99.00000
25%        102.00000
50%        137.00000
75%        159.00000
max        200.00000
Name: SatisfactionIndex, dtype: float64

In [154]:
df["RecencyScore"] = 1 / (df["LastPurchaseDays"]+1)

In [155]:
df["MonetaryScore"] = (
    df["TotalSpend"] *
    df["PurchaseFrequency"]
)

In [156]:
df["FrequencyScore"] = (
    df["TotalTransactions"] /
    df["Tenure"]
)

In [157]:
df["CustomerValueIndex"] = (
    df["TotalSpend"] *
    df["TotalTransactions"] *
    df["CustomerHealthScore"]
)

In [158]:
df["DigitalEngagement"] = (
    df["WebsiteVisits"]+
    df["AppUsageMinutes"]+
    df["LoginFrequency"]
)

In [159]:
df["SatisfactionIndex"] = df["SatisfactionIndex"].clip(0,100)

In [160]:
remove = [
"Gender",
"Location",
"Membership",
"PreferredCategory"
]

In [161]:
features = [

"Age",
"Income",

"Tenure",

"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",

"LastPurchaseDays",

"WebsiteVisits",
"AppUsageMinutes",
"LoginFrequency",

"CustomerHealthScore",

"CustomerValueIndex",
"MonetaryScore",
"FrequencyScore",

"DigitalEngagement",

"SatisfactionScore",
"Rating",

"SupportCalls",
"Complaints"

]

In [163]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


for k in range(2,8):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=20
    )

    labels=model.fit_predict(X_scaled)

    score=silhouette_score(
        X_scaled,
        labels
    )

    print(
        f"K={k}: {score}"
    )

K=2: 0.6297610138102411
K=3: 0.4695121003389785
K=4: 0.47852779181292615
K=5: 0.2526056109004554
K=6: 0.24732137504947346
K=7: 0.2543070878098018

In [164]:
Recency = LastPurchaseDays

Frequency = TotalTransactions

Monetary = TotalSpend

NameError: name 'LastPurchaseDays' is not defined