In [77]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import joblib

In [78]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM-AI/data/raw/customer .csv")

In [79]:
df.head()

,CustomerID,Age,Gender,Income,Location,Membership,RegistrationDate,Tenure,TotalSpend,TotalTransactions,...,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore,ChurnRisk
0,CUST000001,54,Female,72543.43,NJ,Gold,2020-03-10,6.81,4389.80,30,...,48.5,65.6,79,65,3.2,0,2,8.0,31.8,High
1,CUST000002,42,Male,78149.18,AZ,Silver,2021-11-10,5.14,706.89,2,...,87.9,23.4,0,1,0.0,5,18,0.0,11.6,High
2,CUST000003,24,Female,48635.85,MD,Free,2026-08-18,0.37,2935.65,20,...,87.8,62.3,24,55,2.8,7,1,23.0,18.2,High
3,CUST000004,31,Male,19935.67,GA,Free,2025-11-20,1.11,1410.68,32,...,73.0,32.0,23,74,3.7,5,3,3.0,21.0,High
4,CUST000005,45,Female,83500.57,AZ,Silver,2020-03-11,6.80,4352.92,69,...,25.5,59.0,38,77,3.8,4,2,17.0,36.4,High

In [167]:
df.shape

(50000, 36)

In [168]:
df.isnull().sum()

Age                    0
Gender                 0
Income                 0
Location               0
Membership             0
Tenure                 0
TotalSpend             0
TotalTransactions      0
AverageOrderValue      0
PurchaseFrequency      0
LastPurchaseDays       0
PreferredCategory      0
WebsiteVisits          0
AppUsageMinutes        0
LoginFrequency         0
WishlistCount          0
CartAbandonmentRate    0
EmailOpenRate          0
MarketingClicks        0
SatisfactionScore      0
Rating                 0
SupportCalls           0
Complaints             0
Reviews                0
CustomerHealthScore    0
Customer_Segment       0
CustomerValueScore     0
EngagementScore        0
LoyaltyScore           0
SatisfactionIndex      0
PurchaseIntensity      0
RecencyScore           0
MonetaryScore          0
FrequencyScore         0
CustomerValueIndex     0
DigitalEngagement      0
dtype: int64

In [170]:
df.columns

Index(['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure',
       'TotalSpend', 'TotalTransactions', 'AverageOrderValue',
       'PurchaseFrequency', 'LastPurchaseDays', 'PreferredCategory',
       'WebsiteVisits', 'AppUsageMinutes', 'LoginFrequency', 'WishlistCount',
       'CartAbandonmentRate', 'EmailOpenRate', 'MarketingClicks',
       'SatisfactionScore', 'Rating', 'SupportCalls', 'Complaints', 'Reviews',
       'CustomerHealthScore', 'Customer_Segment', 'CustomerValueScore',
       'EngagementScore', 'LoyaltyScore', 'SatisfactionIndex',
       'PurchaseIntensity', 'RecencyScore', 'MonetaryScore', 'FrequencyScore',
       'CustomerValueIndex', 'DigitalEngagement'],
      dtype='str')

In [171]:
df_model.isnull().sum()

Age                    0
Gender                 0
Income                 0
Location               0
Membership             0
Tenure                 0
TotalSpend             0
TotalTransactions      0
AverageOrderValue      0
PurchaseFrequency      0
LastPurchaseDays       0
PreferredCategory      0
WebsiteVisits          0
AppUsageMinutes        0
LoginFrequency         0
WishlistCount          0
CartAbandonmentRate    0
EmailOpenRate          0
MarketingClicks        0
SatisfactionScore      0
Rating                 0
SupportCalls           0
Complaints             0
Reviews                0
CustomerHealthScore    0
EngagementScore        0
LoyaltyScore           0
SatisfactionIndex      0
PurchaseIntensity      0
dtype: int64

In [172]:
from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()


for col in cat_cols:

    df_model[col] = encoder.fit_transform(
        df_model[col]
    )

In [173]:
df_model["CustomerValueScore"] = (
    df_model["TotalSpend"] *
    df_model["TotalTransactions"]
)

In [174]:
df_model["EngagementScore"] = (

df_model["WebsiteVisits"] +
df_model["AppUsageMinutes"] +
df_model["LoginFrequency"]

)

In [175]:
df_model["LoyaltyScore"] = (

df_model["Tenure"] *
df_model["PurchaseFrequency"]

)

In [176]:
df_model["SatisfactionIndex"] = (

df_model["SatisfactionScore"] +
(df_model["Rating"]*20)

)

In [177]:
df_model["PurchaseIntensity"] = (

df_model["TotalTransactions"] /
(df_model["Tenure"]+1)

)

In [178]:
features = [

"Age",
"Income",

"Tenure",

"TotalSpend",
"TotalTransactions",
"AverageOrderValue",
"PurchaseFrequency",

"LastPurchaseDays",

"WebsiteVisits",
"AppUsageMinutes",
"LoginFrequency",

"WishlistCount",
"CartAbandonmentRate",
"EmailOpenRate",

"MarketingClicks",

"SatisfactionScore",
"Rating",

"SupportCalls",
"Complaints",
"Reviews",

"CustomerHealthScore",

"CustomerValueScore",
"EngagementScore",
"LoyaltyScore",
"SatisfactionIndex",
"PurchaseIntensity"

]

In [179]:
X = df_model[features]

In [180]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()


X_scaled = scaler.fit_transform(
    X
)

In [181]:
np.isnan(X_scaled).sum()

np.int64(0)

In [182]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


for k in range(2,6):

    kmeans = KMeans(

        n_clusters=k,
        random_state=42,
        n_init=20

    )


    labels = kmeans.fit_predict(
        X_scaled
    )


    score = silhouette_score(
        X_scaled,
        labels
    )


    print(
        f"K={k}: {score}"
    )

K=2: 0.49109957263772724
K=3: 0.42836611846418376
K=4: 0.2634830520809157
K=5: 0.24935245022924785

In [183]:
kmeans = KMeans(

    n_clusters=3,
    random_state=42,
    n_init=20

)


df_model["Customer_Segment"] = kmeans.fit_predict(
    X_scaled
)

In [184]:
df_model["Customer_Segment"].value_counts()

Customer_Segment
1    32554
2     9925
0     7521
Name: count, dtype: int64

In [185]:
segment_analysis = df_model.groupby(
    "Customer_Segment"
).mean()


segment_analysis

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore,EngagementScore,LoyaltyScore,SatisfactionIndex,PurchaseIntensity,CustomerValueScore
Customer_Segment,,,,,,,,,,,,,,,,,,,,,
0,48.805212,0.489696,190886.596798,9.501662,2.701901,3.527208,49366.574800,120.546736,495.112849,19.132695,...,4.472756,1.503125,0.507778,58.530913,73.474006,3588.591278,67.171949,179.558037,35.493935,5.954212e+06
1,40.414358,0.490754,60527.927144,9.507956,1.492474,3.505097,6072.502535,36.267893,185.578432,5.456902,...,3.608254,3.083891,1.392363,19.721294,31.485314,1039.259200,19.078388,144.354365,10.775968,2.669204e+05
2,46.790932,0.494610,55591.986829,9.395164,1.324433,3.514664,2070.511094,9.963426,386.569248,2.002217,...,1.445280,17.486448,11.452695,5.116373,14.602599,168.606146,7.033326,56.122217,2.922362,2.053176e+04

In [186]:
segment_names = {

0:"Regular Customers",

1:"At Risk Customers",

2:"VIP Customers"

}


df_model["Segment_Name"] = (
    df_model["Customer_Segment"]
    .map(segment_names)
)

In [187]:
import pickle


pickle.dump(
    kmeans,
    open(
        "customer_segmentation.pkl",
        "wb"
    )
)


pickle.dump(
    scaler,
    open(
        "segmentation_scaler.pkl",
        "wb"
    )
)

In [188]:
import joblib

model = joblib.load("../models/customer_segmentation.pkl")
scaler = joblib.load("../models/segmentation_scaler.pkl")

print("Model Loaded")

Model Loaded

In [197]:
test_customer = {
    "Age":45,
    "Gender":0,
    "Income":85000,
    "Location":5,
    "Membership":3,
    "Tenure":5,
    "TotalSpend":12000,
    "TotalTransactions":60,
    "AverageOrderValue":200,
    "PurchaseFrequency":8,
    "LastPurchaseDays":20,
    "PreferredCategory":2,
    "WebsiteVisits":80,
    "AppUsageMinutes":1500,
    "LoginFrequency":70,
    "WishlistCount":20,
    "CartAbandonmentRate":20,
    "EmailOpenRate":70,
    "MarketingClicks":50,
    "SatisfactionScore":85,
    "Rating":4.5,
    "SupportCalls":1,
    "Complaints":0,
    "Reviews":40,
    "CustomerHealthScore":80
}

In [198]:
import pandas as pd

test_df = pd.DataFrame([test_customer])

test_df

,Age,Gender,Income,Location,Membership,Tenure,TotalSpend,TotalTransactions,AverageOrderValue,PurchaseFrequency,...,WishlistCount,CartAbandonmentRate,EmailOpenRate,MarketingClicks,SatisfactionScore,Rating,SupportCalls,Complaints,Reviews,CustomerHealthScore
0,45,0,85000,5,3,5,12000,60,200,8,...,20,20,70,50,85,4.5,1,0,40,80

In [199]:
test_df = pd.DataFrame([test_customer])

In [200]:
test_df.shape

(1, 25)

In [201]:
test_df = test_df[scaler.feature_names_in_]

In [202]:
test_scaled = scaler.transform(test_df)

In [203]:
segment = model.predict(test_scaled)

print("Customer Segment:", segment[0])

Customer Segment: 2

In [204]:
distance = model.transform(test_scaled)

print(distance)

[[1.68950785 1.11489266 0.84476517]]

In [205]:
import pandas as pd
import numpy as np


df = pd.read_csv(
    "customer_behavior.csv"
)


df.shape

FileNotFoundError: [Errno 2] No such file or directory: 'customer_behavior.csv'