In [107]:
pip install pandas numpy scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (1.26.4)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (3.10.6)
Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [108]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [109]:
import warnings
warnings.filterwarnings("ignore")

In [110]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM_AI/data/raw/CLV .csv")

In [111]:
df.head()

,CustomerID,Age,Gender,Income,Location,Membership,RegistrationDate,Tenure,TotalSpend,TotalTransactions,...,CustomerLifetimeValue,NextPurchaseAmount,NextPurchaseDays,DiscountUsed,CouponUsed,ReferralCount,PaymentMethod,DeviceType,ReturnRate,LoyaltyPoints
0,CUST-1001,58,Male,75927,Seattle,Basic,2024-11-15,19.5,3171.20,16,...,5959.50,185.95,41,0,0,1,Apple Pay,Mobile,0.05,31712
1,CUST-1002,66,Male,40538,Los Angeles,Basic,2024-04-14,26.5,12463.47,69,...,20844.34,204.44,6,37,5,2,Credit Card,Mobile,0.11,122784
2,CUST-1003,41,Male,99742,Philadelphia,Gold,2025-03-29,15.1,11819.42,34,...,17037.61,327.34,7,17,2,0,BNPL (Klarna/Afterpay),Desktop,0.08,176441
3,CUST-1004,59,Female,52220,Austin,Basic,2023-11-05,31.8,3657.69,27,...,7580.91,158.07,35,12,9,5,BNPL (Klarna/Afterpay),Mobile,0.14,35976
4,CUST-1005,18,Female,70323,Los Angeles,Gold,2022-08-05,46.8,7877.67,111,...,17058.40,84.22,13,47,10,0,BNPL (Klarna/Afterpay),Tablet,0.15,115815

In [112]:
df.isnull().sum()

CustomerID               0
Age                      0
Gender                   0
Income                   0
Location                 0
Membership               0
RegistrationDate         0
Tenure                   0
TotalSpend               0
TotalTransactions        0
AverageOrderValue        0
PurchaseFrequency        0
LastPurchaseDays         0
PreferredCategory        0
WebsiteVisits            0
AppUsageMinutes          0
LoginFrequency           0
WishlistCount            0
CartAbandonmentRate      0
EmailOpenRate            0
MarketingClicks          0
SatisfactionScore        0
Rating                   0
SupportCalls             0
Complaints               0
Reviews                  0
CustomerHealthScore      0
ChurnRisk                0
CustomerLifetimeValue    0
NextPurchaseAmount       0
NextPurchaseDays         0
DiscountUsed             0
CouponUsed               0
ReferralCount            0
PaymentMethod            0
DeviceType               0
ReturnRate               0
LoyaltyPoints            0
dtype: int64

In [113]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [114]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Location', 'Membership',
       'RegistrationDate', 'Tenure', 'TotalSpend', 'TotalTransactions',
       'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
       'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
       'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
       'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating',
       'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore',
       'ChurnRisk', 'CustomerLifetimeValue', 'NextPurchaseAmount',
       'NextPurchaseDays', 'DiscountUsed', 'CouponUsed', 'ReferralCount',
       'PaymentMethod', 'DeviceType', 'ReturnRate', 'LoyaltyPoints'],
      dtype='object')

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 38 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             250 non-null    object
 1   Age                    250 non-null    int64
 2   Gender                 250 non-null    object
 3   Income                 250 non-null    int64
 4   Location               250 non-null    object
 5   Membership             250 non-null    object
 6   RegistrationDate       250 non-null    object
 7   Tenure                 250 non-null    float64
 8   TotalSpend             250 non-null    float64
 9   TotalTransactions      250 non-null    int64
 10  AverageOrderValue      250 non-null    float64
 11  PurchaseFrequency      250 non-null    float64
 12  LastPurchaseDays       250 non-null    int64
 13  PreferredCategory      250 non-null    object
 14  WebsiteVisits          250 non-null    int64
 15  AppUsageMinutes        250 non-null    int64
 16  LoginFrequency         250 non-null    int64
 17  WishlistCount          250 non-null    int64
 18  CartAbandonmentRate    250 non-null    float64
 19  EmailOpenRate          250 non-null    float64
 20  MarketingClicks        250 non-null    int64
 21  SatisfactionScore      250 non-null    int64
 22  Rating                 250 non-null    float64
 23  SupportCalls           250 non-null    int64
 24  Complaints             250 non-null    int64
 25  Reviews                250 non-null    int64
 26  CustomerHealthScore    250 non-null    int64
 27  ChurnRisk              250 non-null    object
 28  CustomerLifetimeValue  250 non-null    float64
 29  NextPurchaseAmount     250 non-null    float64
 30  NextPurchaseDays       250 non-null    int64
 31  DiscountUsed           250 non-null    int64
 32  CouponUsed             250 non-null    int64
 33  ReferralCount          250 non-null    int64
 34  PaymentMethod          250 non-null    object
 35  DeviceType             250 non-null    object
 36  ReturnRate             250 non-null    float64
 37  LoyaltyPoints          250 non-null    int64
dtypes: float64(10), int64(19), object(9)
memory usage: 74.3+ KB

In [116]:
df.describe

<bound method NDFrame.describe of     CustomerID  Age  Gender  Income      Location Membership RegistrationDate  \
0    CUST-1001   58    Male   75927       Seattle      Basic       2024-11-15
1    CUST-1002   66    Male   40538   Los Angeles      Basic       2024-04-14
2    CUST-1003   41    Male   99742  Philadelphia       Gold       2025-03-29
3    CUST-1004   59  Female   52220        Austin      Basic       2023-11-05
4    CUST-1005   18  Female   70323   Los Angeles       Gold       2022-08-05
..         ...  ...     ...     ...           ...        ...              ...
245  CUST-1246   69    Male   95548        Denver   Platinum       2023-02-21
246  CUST-1247   56    Male   92413       Seattle   Platinum       2022-09-14
247  CUST-1248   46  Female   71376         Miami     Silver       2022-02-12
248  CUST-1249   46  Female   34034       Chicago      Basic       2026-05-26
249  CUST-1250   43  Female   57038        Denver      Basic       2023-03-21

     Tenure  TotalSpend  TotalTransactions  ...  CustomerLifetimeValue  \
0      19.5     3171.20                 16  ...                5959.50
1      26.5    12463.47                 69  ...               20844.34
2      15.1    11819.42                 34  ...               17037.61
3      31.8     3657.69                 27  ...                7580.91
4      46.8     7877.67                111  ...               17058.40
..      ...         ...                ...  ...                    ...
245    40.3     5010.61                101  ...               10717.43
246    45.5     2087.96                 28  ...                5567.17
247    52.6    23554.70                130  ...               50866.73
248     1.2      199.36                  2  ...                1704.34
249    39.4    19917.38                113  ...               37766.23

     NextPurchaseAmount  NextPurchaseDays DiscountUsed  CouponUsed  \
0                185.95                41            0           0
1                204.44                 6           37           5
2                327.34                 7           17           2
3                158.07                35           12           9
4                 84.22                13           47          10
..                  ...               ...          ...         ...
245               48.45                10           35           9
246               91.05                54           26          24
247              190.71                 9           83          58
248              102.73                22            0           0
249              161.82                11           67          55

     ReferralCount           PaymentMethod  DeviceType  ReturnRate  \
0                1               Apple Pay      Mobile        0.05
1                2             Credit Card      Mobile        0.11
2                0  BNPL (Klarna/Afterpay)     Desktop        0.08
3                5  BNPL (Klarna/Afterpay)      Mobile        0.14
4                0  BNPL (Klarna/Afterpay)      Tablet        0.15
..             ...                     ...         ...         ...
245              0               Apple Pay     Desktop        0.01
246              0                  PayPal     Desktop        0.04
247              1             Credit Card     Desktop        0.05
248              1                  PayPal      Mobile        0.09
249              1              Debit Card     Desktop        0.12

     LoyaltyPoints
0            31712
1           122784
2           176441
3            35976
4           115815
..             ...
245          98462
246          40459
247         278506
248           1993
249         195823

[250 rows x 38 columns]>

In [117]:
X.shape, y.shape

((250, 35), (250,))

In [118]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Income', 'Location', 'Membership',
       'RegistrationDate', 'Tenure', 'TotalSpend', 'TotalTransactions',
       'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
       'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
       'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
       'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating',
       'SupportCalls', 'Complaints', 'Reviews', 'CustomerHealthScore',
       'ChurnRisk', 'CustomerLifetimeValue', 'NextPurchaseAmount',
       'NextPurchaseDays', 'DiscountUsed', 'CouponUsed', 'ReferralCount',
       'PaymentMethod', 'DeviceType', 'ReturnRate', 'LoyaltyPoints'],
      dtype='object')

In [119]:
target ="CustomerLifetimeValue"

Encoding

In [176]:
leakage_columns = [

"CustomerID",

"CustomerLifetimeValue",

"TotalSpend",

"TotalTransactions",

"LoyaltyPoints",

"NextPurchaseAmount",

"NextPurchaseDays",

"CustomerHealthScore"

]

In [177]:
X = df.drop(
    leakage_columns,
    axis=1
)

In [178]:
X.shape

(250, 30)

In [179]:
X.dtypes

Age                      int64
Gender                  object
Income                   int64
Location                object
Membership              object
RegistrationDate        object
Tenure                 float64
AverageOrderValue      float64
PurchaseFrequency      float64
LastPurchaseDays         int64
PreferredCategory       object
WebsiteVisits            int64
AppUsageMinutes          int64
LoginFrequency           int64
WishlistCount            int64
CartAbandonmentRate    float64
EmailOpenRate          float64
MarketingClicks          int64
SatisfactionScore        int64
Rating                 float64
SupportCalls             int64
Complaints               int64
Reviews                  int64
ChurnRisk               object
DiscountUsed             int64
CouponUsed               int64
ReferralCount            int64
PaymentMethod           object
DeviceType              object
ReturnRate             float64
dtype: object

In [180]:
cat_cols = X.select_dtypes(
    include="object"
).columns


encoder = LabelEncoder()


for col in cat_cols:

    X[col] = encoder.fit_transform(
        X[col]
    )

In [181]:
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42

)

In [182]:
X_train.shape, X_test.shape

((200, 30), (50, 30))

In [183]:
scaler = StandardScaler()


X_train_scaled = scaler.fit_transform(
    X_train
)


X_test_scaled = scaler.transform(
    X_test
)

In [184]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    ExtraTreesRegressor
)

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [185]:
models = {


"Linear Regression":
LinearRegression(),


"Random Forest":
RandomForestRegressor(
    n_estimators=200,
    random_state=42
),


"Gradient Boosting":
GradientBoostingRegressor(
    random_state=42
),


"Extra Trees":
ExtraTreesRegressor(
    n_estimators=200,
    random_state=42
),


"XGBoost":
XGBRegressor(
    random_state=42
),


"LightGBM":
LGBMRegressor(
    random_state=42
),


"CatBoost":
CatBoostRegressor(
    verbose=0
)

}

In [186]:
results=[]


for name,model in models.items():

    print(
        "Training",
        name
    )


    model.fit(
        X_train_scaled,
        y_train
    )


    pred=model.predict(
        X_test_scaled
    )


    results.append({

        "Model":name,

        "MAE":
        mean_absolute_error(
            y_test,
            pred
        ),


        "RMSE":
        np.sqrt(
            mean_squared_error(
                y_test,
                pred
            )
        ),


        "R2 Score":
        r2_score(
            y_test,
            pred
        )

    })

Training Linear Regression
Training Random Forest
Training Gradient Boosting
Training Extra Trees
Training XGBoost
Training LightGBM
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000102 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 936
[LightGBM] [Info] Number of data points in the train set: 200, number of used features: 30
[LightGBM] [Info] Start training from score 20312.025988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training CatBoost

In [187]:
results_df = pd.DataFrame(results)

results_df.sort_values(
    "R2 Score",
    ascending=False
)

               Model          MAE          RMSE  R2 Score
3        Extra Trees  4058.297498   6541.943424  0.906586
2  Gradient Boosting  4161.455419   6557.762741  0.906134
6           CatBoost  3748.329573   6843.246854  0.897784
5           LightGBM  4863.153372   7967.928600  0.861424
1      Random Forest  5432.263696   8567.661872  0.839778
0  Linear Regression  6564.368786   9019.169158  0.822446
4            XGBoost  6068.225173  10044.385004  0.779787

In [188]:
X["RegistrationDate"] = pd.to_datetime(
    X["RegistrationDate"]
)


X["RegistrationYear"] = X["RegistrationDate"].dt.year

X["RegistrationMonth"] = X["RegistrationDate"].dt.month


X = X.drop(
    "RegistrationDate",
    axis=1
)

In [189]:
cat_cols = X.select_dtypes(
    include="object"
).columns


num_cols = X.select_dtypes(
    exclude="object"
).columns



cat_cols, num_cols

(Index([], dtype='object'),
 Index(['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure',
        'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
        'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
        'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
        'EmailOpenRate', 'MarketingClicks', 'SatisfactionScore', 'Rating',
        'SupportCalls', 'Complaints', 'Reviews', 'ChurnRisk', 'DiscountUsed',
        'CouponUsed', 'ReferralCount', 'PaymentMethod', 'DeviceType',
        'ReturnRate', 'RegistrationYear', 'RegistrationMonth'],
       dtype='object'))

In [190]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer


preprocessor = ColumnTransformer(

transformers=[

(
"num",
StandardScaler(),
num_cols
),

(
"cat",
OneHotEncoder(
handle_unknown="ignore"
),
cat_cols
)

]

)

In [191]:
from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test = train_test_split(

X,
y,

test_size=0.2,

random_state=42

)

In [192]:
X_train_scaled = preprocessor.fit_transform(
    X_train
)


X_test_scaled = preprocessor.transform(
    X_test
)

In [193]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
RandomForestRegressor,
GradientBoostingRegressor,
ExtraTreesRegressor
)

from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor



models={

"Linear Regression":
LinearRegression(),


"Random Forest":
RandomForestRegressor(
n_estimators=300,
random_state=42
),


"Gradient Boosting":
GradientBoostingRegressor(
random_state=42
),


"Extra Trees":
ExtraTreesRegressor(
n_estimators=300,
random_state=42
),


"XGBoost":
XGBRegressor(
random_state=42
),


"CatBoost":
CatBoostRegressor(
verbose=0
),


"LightGBM":
LGBMRegressor()

}

In [194]:
from sklearn.metrics import (
mean_absolute_error,
mean_squared_error,
r2_score
)


results=[]


for name,model in models.items():

    print(
        "Training",
        name
    )


    model.fit(
        X_train_scaled,
        y_train
    )


    pred=model.predict(
        X_test_scaled
    )


    results.append({

    "Model":name,

    "MAE":
    mean_absolute_error(
        y_test,
        pred
    ),

    "RMSE":
    np.sqrt(
        mean_squared_error(
        y_test,
        pred)
    ),

    "R2 Score":
    r2_score(
        y_test,
        pred
    )

    })



results_df=pd.DataFrame(results)

results_df.sort_values(
"R2 Score",
ascending=False
)

Training Linear Regression
Training Random Forest
Training Gradient Boosting
Training Extra Trees
Training XGBoost
Training CatBoost
Training LightGBM
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000194 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 869
[LightGBM] [Info] Number of data points in the train set: 200, number of used features: 29
[LightGBM] [Info] Start training from score 20312.025988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

               Model          MAE         RMSE  R2 Score
3        Extra Trees  4057.943929  6696.511562  0.902120
2  Gradient Boosting  4190.537089  6723.566165  0.901328
5           CatBoost  3908.033694  7382.893691  0.881027
6           LightGBM  4953.822017  7665.211787  0.871754
1      Random Forest  5388.154377  8428.855985  0.844928
0  Linear Regression  6456.063730  8973.492819  0.824240
4            XGBoost  5732.746716  9664.750583  0.796119

In [196]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import ExtraTreesRegressor
import joblib
import os


best_model = Pipeline(

[
    (
        "preprocessor",
        preprocessor
    ),

    (
        "model",
        ExtraTreesRegressor(
            n_estimators=300,
            random_state=42
        )
    )
]

)


best_model.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Age', 'Gender', 'Income', 'Location', 'Membership', 'Tenure',
       'AverageOrderValue', 'PurchaseFrequency', 'LastPurchaseDays',
       'PreferredCategory', 'WebsiteVisits', 'AppUsageMinutes',
       'LoginFrequency', 'WishlistCount', 'CartAbandonmentRate',
       'EmailOpenRate', 'MarketingClic...nScore', 'Rating',
       'SupportCalls', 'Complaints', 'Reviews', 'ChurnRisk', 'DiscountUsed',
       'CouponUsed', 'ReferralCount', 'PaymentMethod', 'DeviceType',
       'ReturnRate', 'RegistrationYear', 'RegistrationMonth'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model',
                 ExtraTreesRegressor(n_estimators=300, random_state=42))])

In [200]:
import os

os.makedirs(
    "models",
    exist_ok=True
)

In [198]:
os.listdir()

['03_SegmentationV(2).ipynb',
 '02_Feature_Engineering.ipynb',
 '07_Recommendation.ipynb',
 '06_Next_Purchase.ipynb',
 '01_EDA.ipynb',
 '04_Churn.ipynb',
 '08_Fraud.ipynb',
 '.ipynb_checkpoints',
 '05_CLV.ipynb',
 'catboost_info']

In [201]:
import joblib

joblib.dump(
    best_model,
    "models/clv_model.pkl"
)

['models/clv_model.pkl']

In [202]:
features = X.columns.tolist()

joblib.dump(
    features,
    "models/clv_features.pkl"
)

['models/clv_features.pkl']