In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    ExtraTreesRegressor
)

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

import joblib

In [3]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM_AI/data/raw/behaviour .csv")

In [4]:
df.head()

,CustomerID,WebsiteVisits,AppUsage,SupportCalls,Complaints,Reviews,WishlistCount,CartAbandonment,SatisfactionScore
0,CUST000001,23,167.8,3,2,4,2,2,2.5
1,CUST000002,19,143.3,5,3,5,1,2,2.8
2,CUST000003,23,234.4,0,0,3,6,2,4.1
3,CUST000004,19,223.8,3,2,6,6,0,4.3
4,CUST000005,25,151.0,4,0,3,5,1,4.1

In [5]:
df = pd.read_csv("/Users/aashishmewada/Desktop/PRISM AI/PRISM_AI/data/raw/transactions .csv")

In [6]:
df.head()

,TransactionID,CustomerID,Date,ProductID,Category,Price,Quantity,Discount,PaymentMethod
0,TXN00000001,CUST000001,2026-01-07 02:52:00,ELEC-104,Electronics,49.99,1,0.00,Credit Card
1,TXN00000002,CUST000001,2025-11-17 09:16:00,APPR-202,Apparel,45.00,2,0.00,Credit Card
2,TXN00000003,CUST000002,2024-05-22 00:51:00,SPRT-602,Sports,55.00,2,0.10,Apple Pay
3,TXN00000004,CUST000002,2024-10-26 23:52:00,ELEC-103,Electronics,199.50,2,0.05,Credit Card
4,TXN00000005,CUST000002,2025-03-04 08:47:00,APPR-203,Apparel,120.00,1,0.05,PayPal